### PR TITLE
feat: Add VPNStatus cask

### PR DESCRIPTION
**Pull request by dronenb**
Add VPNStatus cask. Will rebase once #1 is merged and advance from draft state.

### CODE REVIEW

**Comment by dronenb** [comment]
actually I guess since there won't be any conflicts it won't matter...

**Comment by dronenb** [comment]
@Timac are there any other files other than `~/Library/Preferences/org.timac.VPNStatus.plist` that the user should clean up during an uninstall? If not I think this is G2G assuming it passes CI.

**Comment by Timac** [comment]
> @Timac are there any other files other than `~/Library/Preferences/org.timac.VPNStatus.plist` that the user should clean up during an uninstall? If not I think this is G2G assuming it passes CI.

`~/Library/Preferences/org.timac.VPNStatus.plist` should be the only file to remove

**Comment by Timac** [comment]
Thanks again for helping on the Homebrew integration!

**Pull request merged**
